### ISSUE TITLE
Custom Resource rewrite

### ISSUE THREAD

**Issue by damacus** [sous-chefs/graphite#276]
This ticket is to track the progress of the custom resource rewrite. 

- [ ] Accumulator #230 
- [ ] Uses poise-python #254 
- [ ] Tests to cover #247 
- [ ] Doesn't reinstall Twist every time #221 
- [ ] Optional backend install #
- [ ] Optional API install #184
